name: Ejecutar Playwright Async cada 30 min

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: # Esto permite ejecutarlo manualmente para probar

jobs:
  playwright-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest-playwright
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Instalar Navegadores de Playwright
        run: playwright install --with-deps chromium

      - name: Ejecutar script Async
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          CNBV_USER: ${{ secrets.CNBV_USER }}
          CNBV_PASS: ${{ secrets.CNBV_PASS }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_DEST: ${{ secrets.EMAIL_DEST }}
          URL_LOGIN: ${{ secrets.URL_LOGIN }}
          URL_CONSULTA: ${{ secrets.URL_CONSULTA }}
          GCP_TYPE: ${{ secrets.GCP_TYPE }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_PRIVATE_KEY_ID: ${{ secrets.GCP_PRIVATE_KEY_ID }}
          GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
          GCP_CLIENT_EMAIL: ${{ secrets.GCP_CLIENT_EMAIL }}
          GCP_CLIENT_ID: ${{ secrets.GCP_CLIENT_ID }}
          GCP_AUTH_URI: ${{ secrets.GCP_AUTH_URI }}
          GCP_TOKEN_URI: ${{ secrets.GCP_TOKEN_URI }}
          GCP_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.GCP_AUTH_PROVIDER_X509_CERT_URL }}
          GCP_CLIENT_X509_CERT_URL: ${{ secrets.GCP_CLIENT_X509_CERT_URL }}
          GCP_UNIVERSE_DOMAIN: ${{ secrets.GCP_UNIVERSE_DOMAIN }}
          
        run: python main.py
